name: gitkraken
version: '3.5.0'
summary: Unleash your repo.
description: |
  The best Git client should integrate with your Git hosting service. That’s why GitKraken connects to popular services like GitHub, Bitbucket and GitLab to make working with your remote repositories easier.

grade: stable
architectures: [amd64]
confinement: strict

parts:
  gitkraken:
    plugin: dump
    source: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    source-type: deb
    build-packages:
      - execstack
    prepare: |
      sed -i 's|Icon=app|Icon=/usr/share/pixmaps/app\.png|' usr/share/applications/gitkraken.desktop
      execstack --clear-execstack usr/share/gitkraken/gitkraken
      execstack --clear-execstack usr/share/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node
      rm -r usr/bin
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - gconf-service
      - libnotify4
      - libxtst6
      - libxkbfile1
      - libxss1
      - libnss3
      - librtmp1
      - libcurl3
      - python
      - gvfs-bin
      - libgnome-keyring0
      - gir1.2-gnomekeyring-1.0
      - libcanberra-gtk-module
      - libatk-adaptor
      - libgail-common
      - overlay-scrollbar-gtk2

apps:
  gitkraken:
    command: bin/desktop-launch $SNAP/usr/share/gitkraken/gitkraken
    desktop: usr/share/applications/gitkraken.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media
      - ssh-public-keys
